---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5ecea938cd990c0014799f4d/webhook/forestry
sections:
  - type: document
    label: Site Configuration
    path: site-metadata.json
    templates:
      - config
  - type: directory
    path: src/pages
    match: '**/*'
    exclude: '{blog/index.md,portfolio/index.md}'
    label: Advanced Page
    create: all
    templates:
      - advanced
  - type: document
    label: Blog
    path: src/pages/blog/index.md
    templates:
      - blog
  - type: document
    label: Portfolio
    path: src/pages/portfolio/index.md
    templates:
      - portfolio
  - type: directory
    path: src/pages
    match: '**/*'
    exclude: '{posts/**,blog/index.md,portfolio/index.md}'
    label: Page
    create: all
    templates:
      - page
  - type: directory
    path: src/pages/posts
    match: '**/*'
    label: Post
    create: all
    templates:
      - post
  - type: directory
    path: src/pages/projects
    match: '**/*'
    label: Project
    create: all
    templates:
      - project
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
